### PR TITLE
Change / Add biomes with birches in mgv5/7

### PR DESCRIPTION
**Pull request by jbruechert**
Birches in sandstone grassland
- use birches as decoration for sandstone grasslands too

### CODE REVIEW

**Comment by lnjX** [comment]
I don't think that birches should only be generated in sandstone grasslands.
Should be either both deciduous_forest and sandstone_grassland or in deciduous_forest and a new biome!

**Comment by jbruechert** [comment]
Ok, I think so too. I just wanted to give the sandstone grassland more sense. And the birches sometimes are generated into other trees because the "Trees" spawn too often that the birches have enough space. Maybe we could optimize the spawn chance a bit?

**Comment by lnjX** [comment]
Yeah do it!

**Comment by lnjX** [comment]
Closed due to inactivity.

**Comment by jbruechert** [comment]
In my opinion it's ready to merge, I checked the spawn rate and it was ok.

**Comment by lnjX** [comment]
But your branch is not up to date and there are merge conflicts.

**Comment by lnjX** [comment]
Merged: https://github.com/Gamerbude/Minetest_TNG/commit/2f5299ece412121143c06871c09a0e8608682b55

**Pull request closed without merging**
