### PR TITLE
Add cherry, maple and red maple trees

### PR DESCRIPTION
**Pull request by lnjX**
TODO:
- [x] Add trees
- [x] Add textures
- [x] Add schemeatics
- [x] Add biomes (maple, red maple + maple, only red maple)
- [x] Add tree schematic decorations

### CODE REVIEW

**Comment by jbruechert** [comment]
Some textures:
defaultmaplemapletestred

defaultmaplemapletest

and of course maple wood:

... and tree
default_maple_tree

maple leaves with autumn effects:
defaultmapleautum

An old birch texture:
birch_leaves

default_cherry_leaves

default_cherry_leaves_simple

a cherry tree texture by rui914
rui_default_cherry_tree

Simple variants of the leaves:
default_red_maple_leaves_simple
default_maple_leaves_simple
default_maple_leaves_autum_simple

**Comment by lnjX** [comment]
And please don't forget the simple variants. :)

**Comment by lnjX** [comment]
https://github.com/Rui914/Japanese_Modpack/issues/1

**Comment by lnjX** [comment]
take_sakura_tree
take_sakura_tree_top
Cherry Tree textures by rui914; WTFPL

**Comment by lnjX** [comment]
We've got nodes, textures and schematics! :smiley_cat: 
So only the generation is missing, but that shouldn't be a problem.

**Comment by jbruechert** [comment]
cool, I'm looking forward to the new look of the maps!

**Comment by lnjX** [comment]
screenshot_20160430_112632
The first naturally generated maple trees! :smiley:

**Comment by lnjX** [comment]
screenshot_20160430_114039
screenshot_20160430_114247

**Comment by lnjX** [comment]
At the moment cherry trees are not generated. :(
have to fix that...

**Comment by lnjX** [comment]
@JBBgameich Is this ok? I think I am finished with it.
Cherry Trees are fixed.

**Comment by jbruechert** [comment]
Ok I think it's ready. I'm just. Online on my phone, should I try to merge?

**Comment by lnjX** [comment]
then merge it

**Comment by jbruechert** [comment]
I can't squash and change the  title in octodroid.

**Comment by lnjX** [comment]
Then why are you using octodroid?

**Comment by lnjX** [comment]
GitHub has a website... :100:

**Pull request merged**
