### PR TITLE
Add garden soil

### PR DESCRIPTION
**Pull request by lnjX**
Onto garden soil plants don't need water to grow.

Texture is by @cdqwertz

I think this PR is ready for merge.

### CODE REVIEW

**Comment by jbruechert** [comment]
ok, but how to get garden soil?

**Comment by lnjX** [comment]
@JBBgameich At the moment its not possible to get it. But later I want to add a compost bin where you can compost plants to compost.

|  |  |  |
| --- | --- | --- |
| Compost | Bone Meal | Compost |
| Compost | Dirt | Compost |
| Compost | Compost | Compost |

**Comment by jbruechert** [comment]
could you add a simple crafting recepie like this for the time there isn't a composter (I know its too hard but better then nothing): default:dirt + water bucket --> garden soil + bucket empty?

**Comment by lnjX** [comment]
But how do you want to do that with the empty bucket?

**Comment by jbruechert** [comment]
like this:
replacements = { {"bucket:bucket_water", "bucket:bucket_empty"}, },

**Comment by lnjX** [comment]
Ok.
Work in Progress...

**Comment by lnjX** [comment]
Added.
Please add this to the commit description, if you merge it.

On garden soil plants don't need water to grow.
You can craft it by a bucket with water and dirt.

**Comment by jbruechert** [comment]
ok I merge it!

**Pull request merged**
